// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCompressJob(arg1:Array<string>,arg2:string,arg3:string):Promise<number>;

export function AddCopyJob(arg1:Array<string>,arg2:string,arg3:string):Promise<number>;

export function AddDeleteJob(arg1:Array<string>):Promise<number>;

export function AddExtractJob(arg1:string,arg2:string,arg3:string):Promise<number>;

export function AddMoveJob(arg1:Array<string>,arg2:string,arg3:string):Promise<number>;

export function CancelJob(arg1:number):Promise<void>;

export function GetJobs():Promise<Array<Record<string, any>>>;

export function ListDirectory(arg1:string):Promise<Array<Record<string, any>>>;

export function ListRoots():Promise<Array<string>>;
