// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCompressJob(arg1, arg2, arg3) {
  return window['go']['api']['API']['AddCompressJob'](arg1, arg2, arg3);
}

export function AddCopyJob(arg1, arg2, arg3) {
  return window['go']['api']['API']['AddCopyJob'](arg1, arg2, arg3);
}

export function AddDeleteJob(arg1) {
  return window['go']['api']['API']['AddDeleteJob'](arg1);
}

export function AddExtractJob(arg1, arg2, arg3) {
  return window['go']['api']['API']['AddExtractJob'](arg1, arg2, arg3);
}

export function AddMoveJob(arg1, arg2, arg3) {
  return window['go']['api']['API']['AddMoveJob'](arg1, arg2, arg3);
}

export function CancelJob(arg1) {
  return window['go']['api']['API']['CancelJob'](arg1);
}

export function GetJobs() {
  return window['go']['api']['API']['GetJobs']();
}

export function ListDirectory(arg1) {
  return window['go']['api']['API']['ListDirectory'](arg1);
}

export function ListRoots() {
  return window['go']['api']['API']['ListRoots']();
}
